### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by micha223** [SouravJohar/handy#12]
![error](https://user-images.githubusercontent.com/72801235/95859002-3ad42280-0d5e-11eb-9441-fcf53af210e7.png)

Hello,
When I run test.py, I get the following error:

[ WARN:0] global /tmp/pip-wheel-frffvd08/opencv-python/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "/home/pi/Documents/handy-master/test.py", line 5, in <module>
    hist = handy.capture_histogram(source=0)
  File "/home/pi/Documents/handy-master/handy.py", line 27, in capture_histogram
    frame = cv2.resize(frame, (1000,600))
cv2.error: OpenCV(4.4.0) /tmp/pip-wheel-frffvd08/opencv-python/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Who can help me? What's going wrong and what is the solution?

**Comment by micha223** [comment]
I have fixt it. I have to do invert the lines:

hist = handy.capture_histogram(source=0)
cap = cv2.VideoCapture(0)
